# Generated by Django 6.0.5 on 2026-06-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MercadoParceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=500, verbose_name="Endereço")),
            ],
            options={
                "verbose_name": "Mercado Parceiro",
                "verbose_name_plural": "Mercados Parceiros",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "preco_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Original"
                    ),
                ),
                (
                    "preco_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço com Desconto",
                    ),
                ),
                ("validade", models.DateField(verbose_name="Validade")),
                (
                    "mercado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="Produtos.mercadoparceiro",
                        verbose_name="Mercado Parceiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["validade"],
            },
        ),
    ]
