# Generated by Django 6.0.5 on 2026-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
