# Generated by Django 6.0.6 on 2026-06-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produtos", "0002_produto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL da Imagem"
            ),
        ),
    ]
